const { __ } = wp.i18n;

export const options = {
	speedControls : [
		{ label: __( 'Default', 'kungfu' ), value: '' },
		{ label: __( 'Slower', 'kungfu' ), value: 'slower' },
		{ label: __( 'Slow', 'kungfu' ), value: 'slow' },
		{ label: __( 'Fast', 'kungfu' ), value: 'fast' },
		{ label: __( 'Faster', 'kungfu' ), value: 'faster' },
	],
	delayControls : [
		{ label: __( 'Default', 'kungfu' ), value: '' },
		{ label: __( '100 milliseconds', 'kungfu' ), value: 'delay-100ms' },
		{ label: __( '200 milliseconds', 'kungfu' ), value: 'delay-200ms' },
		{ label: __( '500 milliseconds', 'kungfu' ), value: 'delay-500ms' },
		{ label: __( 'One second', 'kungfu' ), value: 'delay-1s' },
		{ label: __( 'Two seconds', 'kungfu' ), value: 'delay-2s' },
		{ label: __( 'Three seconds', 'kungfu' ), value: 'delay-3s' },
		{ label: __( 'Four seconds', 'kungfu' ), value: 'delay-4s' },
		{ label: __( 'Five seconds', 'kungfu' ), value: 'delay-5s' },
	],
	styleControls : [
		{ label: __( 'Default', 'kungfu' ), value: '' },
		{
			label: __( 'Attention Seekers', 'kungfu' ),
			value: null,
			disabled: true,
		},
		{ label: __( 'Bounce', 'kungfu' ), value: 'bounce' },
		{ label: __( 'Flash', 'kungfu' ), value: 'flash' },
		{ label: __( 'Pulse', 'kungfu' ), value: 'pulse' },
		{ label: __( 'Rubber Band', 'kungfu' ), value: 'rubberBand' },
		{ label: __( 'ShakeX', 'kungfu' ), value: 'shakeX' },
		{ label: __( 'ShakeY', 'kungfu' ), value: 'shakeY' },
		{ label: __( 'Head Shake', 'kungfu' ), value: 'headShake' },
		{ label: __( 'Swing', 'kungfu' ), value: 'swing' },
		{ label: __( 'TaDa', 'kungfu' ), value: 'tada' },
		{ label: __( 'Wobble', 'kungfu' ), value: 'wobble' },
		{ label: __( 'Jello', 'kungfu' ), value: 'jello' },
		{ label: __( 'Heart Beat', 'kungfu' ), value: 'heartBeat' },
		{
			label: __( 'Back Entrances', 'kungfu' ),
			value: null,
			disabled: true,
		},
		{ label: __( 'Bounce In Down', 'kungfu' ), value: 'bounceInDown' },
		{ label: __( 'Bounce In Left', 'kungfu' ), value: 'bounceInLeft' },
		{ label: __( 'Bounce In Right', 'kungfu' ), value: 'bounceInRight' },
		{ label: __( 'Bounce In Up', 'kungfu' ), value: 'bounceInUp' },
		{
			label: __( 'Back Exits', 'kungfu' ),
			value: null,
			disabled: true,
		},
		{ label: __( 'Bounce Out Down', 'kungfu' ), value: 'bounceOutDown' },
		{ label: __( 'Bounce Out Left', 'kungfu' ), value: 'bounceOutLeft' },
		{ label: __( 'Bounce Out Right', 'kungfu' ), value: 'bounceOutRight' },
		{ label: __( 'Bounce Out Up', 'kungfu' ), value: 'bounceOutUp' },
		{
			label: __( 'Bouncing Entrances', 'kungfu' ),
			value: null,
			disabled: true,
		},
		{ label: __( 'Bounce In', 'kungfu' ), value: 'bounceIn' },
		{ label: __( 'Bounce In Down', 'kungfu' ), value: 'bounceInDown' },
		{ label: __( 'Bounce In Left', 'kungfu' ), value: 'bounceInLeft' },
		{ label: __( 'Bounce In Right', 'kungfu' ), value: 'bounceInRight' },
		{ label: __( 'Bounce In Up', 'kungfu' ), value: 'bounceInUp' },
		{
			label: __( 'Bouncing Exits', 'kungfu' ),
			value: null,
			disabled: true,
		},
		{ label: __( 'Bounce Out', 'kungfu' ), value: 'bounceOut' },
		{ label: __( 'Bounce Out Down', 'kungfu' ), value: 'bounceOutDown' },
		{ label: __( 'Bounce Out Left', 'kungfu' ), value: 'bounceOutLeft' },
		{ label: __( 'Bounce Out Right', 'kungfu' ), value: 'bounceOutRight' },
		{ label: __( 'Bounce Out Up', 'kungfu' ), value: 'bounceOutUp' },
		{
			label: __( 'Fading Entrances', 'kungfu' ),
			value: null,
			disabled: true,
		},
		{ label: __( 'Fade In', 'kungfu' ), value: 'fadeIn' },
		{ label: __( 'Fade In Down', 'kungfu' ), value: 'fadeInDown' },
		{ label: __( 'Fade In Left', 'kungfu' ), value: 'fadeInLeft' },
		{ label: __( 'Fade In Right', 'kungfu' ), value: 'fadeInRight' },
		{ label: __( 'Fade In Up', 'kungfu' ), value: 'fadeInUp' },
		{ label: __( 'Fade In Top Left', 'kungfu' ), value: 'fadeInTopLeft' },
		{ label: __( 'Fade In Top Right', 'kungfu' ), value: 'fadeInTopRight' },
		{ label: __( 'Fade In Bottom Left', 'kungfu' ), value: 'fadeInBottomLeft' },
		{ label: __( 'Fade In Bottom Right', 'kungfu' ), value: 'fadeInBottomRight' },
		{
			label: __( 'Fading Exits', 'kungfu' ),
			value: null,
			disabled: true,
		},
		{ label: __( 'Fade Out', 'kungfu' ), value: 'fadeOut' },
		{ label: __( 'Fade Out Down', 'kungfu' ), value: 'fadeOutDown' },
		{ label: __( 'Fade Out Left', 'kungfu' ), value: 'fadeOutLeft' },
		{ label: __( 'Fade Out Right', 'kungfu' ), value: 'fadeOutRight' },
		{ label: __( 'Fade Out Up', 'kungfu' ), value: 'fadeOutUp' },
		{ label: __( 'Fade Out Top Left', 'kungfu' ), value: 'fadeOutTopLeft' },
		{ label: __( 'Fade Out Top Right', 'kungfu' ), value: 'fadeOutTopRight' },
		{ label: __( 'Fade Out Bottom Left', 'kungfu' ), value: 'fadeOutBottomLeft' },
		{ label: __( 'Fade Out Bottom Right', 'kungfu' ), value: 'fadeOutBottomRight' },
		{
			label: __( 'Flippers', 'kungfu' ),
			value: null,
			disabled: true,
		},
		{ label: __( 'Flip', 'kungfu' ), value: 'flip' },
		{ label: __( 'Flip In X', 'kungfu' ), value: 'flipInX' },
		{ label: __( 'Flip In Y', 'kungfu' ), value: 'flipInY' },
		{ label: __( 'Flip Out X', 'kungfu' ), value: 'flipOutX' },
		{ label: __( 'Flip Out Y', 'kungfu' ), value: 'flipOutY' },
		{
			label: __( 'Lightspeed', 'kungfu' ),
			value: null,
			disabled: true,
		},
		{ label: __( 'Light Speed In Left', 'kungfu' ), value: 'lightSpeedInLeft' },
		{ label: __( 'Light Speed In Right', 'kungfu' ), value: 'lightSpeedInRight' },
		{ label: __( 'Light Speed Out Left', 'kungfu' ), value: 'lightSpeedOutLeft' },
		{ label: __( 'Light Speed Out Right', 'kungfu' ), value: 'lightSpeedOutRight' },
		{
			label: __( 'Rotating Entrances', 'kungfu' ),
			value: null,
			disabled: true,
		},
		{ label: __( 'Rotate In', 'kungfu' ), value: 'rotateIn' },
		{ label: __( 'Rotate In Down Left', 'kungfu' ), value: 'rotateInDownLeft' },
		{ label: __( 'Rotate In Down Right', 'kungfu' ), value: 'rotateInDownRight' },
		{ label: __( 'Rotate In Up Left', 'kungfu' ), value: 'rotateInUpLeft' },
		{ label: __( 'Rotate In Up Right', 'kungfu' ), value: 'rotateInUpRight' },
		{
			label: __( 'Rotating Exits', 'kungfu' ),
			value: null,
			disabled: true,
		},
		{ label: __( 'Rotate Out', 'kungfu' ), value: 'rotateOut' },
		{ label: __( 'Rotate Out Down Left', 'kungfu' ), value: 'rotateOutDownLeft' },
		{ label: __( 'Rotate Out Down Right', 'kungfu' ), value: 'rotateOutDownRight' },
		{ label: __( 'Rotate Out Up Left', 'kungfu' ), value: 'rotateOutUpLeft' },
		{ label: __( 'Rotate Out Up Right', 'kungfu' ), value: 'rotateOutUpRight' },
		{
			label: __( 'Specials', 'kungfu' ),
			value: null,
			disabled: true,
		},
		{ label: __( 'Hinge', 'kungfu' ), value: 'hinge' },
		{ label: __( 'Jack In The Box', 'kungfu' ), value: 'jackInTheBox' },
		{ label: __( 'Roll In', 'kungfu' ), value: 'rollIn' },
		{ label: __( 'Roll Out', 'kungfu' ), value: 'rollOut' },
		{
			label: __( 'Zooming Entrances', 'kungfu' ),
			value: null,
			disabled: true,
		},
		{ label: __( 'Zoom In', 'kungfu' ), value: 'zoomIn' },
		{ label: __( 'Zoom In Down', 'kungfu' ), value: 'zoomInDown' },
		{ label: __( 'Zoom In Left', 'kungfu' ), value: 'zoomInLeft' },
		{ label: __( 'Zoom In Right', 'kungfu' ), value: 'zoomInRight' },
		{ label: __( 'Zoom In Up', 'kungfu' ), value: 'zoomInUp' },
		{
			label: __( 'Zooming Exits', 'kungfu' ),
			value: null,
			disabled: true,
		},
		{ label: __( 'Zoom Out', 'kungfu' ), value: 'zoomOut' },
		{ label: __( 'Zoom Out Down', 'kungfu' ), value: 'zoomOutDown' },
		{ label: __( 'Zoom Out Left', 'kungfu' ), value: 'zoomOutLeft' },
		{ label: __( 'Zoom Out Right', 'kungfu' ), value: 'zoomOutRight' },
		{ label: __( 'Zoom Out Up', 'kungfu' ), value: 'zoomOutUp' },
		{
			label: __( 'Sliding Entrances', 'kungfu' ),
			value: null,
			disabled: true,
		},
		{ label: __( 'Slide In Down', 'kungfu' ), value: 'slideInDown' },
		{ label: __( 'Slide In Left', 'kungfu' ), value: 'slideInLeft' },
		{ label: __( 'Slide In Right', 'kungfu' ), value: 'slideInRight' },
		{ label: __( 'Slide In Up', 'kungfu' ), value: 'slideInUp' },
		{
			label: __( 'Sliding Exits', 'kungfu' ),
			value: null,
			disabled: true,
		},
		{ label: __( 'Slide Out Down', 'kungfu' ), value: 'slideOutDown' },
		{ label: __( 'Slide Out Left', 'kungfu' ), value: 'slideOutLeft' },
		{ label: __( 'Slide Out Right', 'kungfu' ), value: 'slideOutRight' },
		{ label: __( 'Slide Out Up', 'kungfu' ), value: 'slideOutUp' },
	],
}